### ISSUE TITLE
WebCmdletIEDomNotSupportedException when running UpdateThumbprint-RollForward.ps1

### ISSUE THREAD

**Issue by Jan-Kruse** [AzureAD/azure-activedirectory-powershell-tokenkey#5]
This error occurs for me when running the script:

Invoke-WebRequest : Der Antwortinhalt kann nicht analysiert werden, da das Internet Explorer-Modul nicht verfügbar ist, oder die Konfiguration beim ersten Start von Internet Explorer ist nicht abgeschlossen. Geben Sie den UseBasicParsing-Parameter an, und wiederholen Sie den Vorgang.
In C:\Users\JanKruse\Documents\WindowsPowerShell\Modules\AADGraph\Cmdlets\AADGraphObject.psm1:9 Zeichen:15
- ...   $result = Invoke-WebRequest -Method Get -Uri $uri -Headers @{"Autho ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
  - FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
    d

Service principal was not found - please check the Client (Application) ID

**Comment by Jan-Kruse** [comment]
It occurs, when not having Internet Explorer run on the machine yet

**Comment by Takou-DevAp** [comment]
> It occurs, when not having Internet Explorer run on the machine yet
Hi @Jan-Kruse ,
Please What do you mean? I'm facing the same issue but within another context...
